### ISSUE TITLE
how to use stylus?

### ISSUE THREAD

**Issue by zhanghanbing1998** [vuesion/vuesion#419]
**I'm sorry to bother you again. I used stylus in my previous project and had an error integrating it into vuesion. How do I use stylus?**

```
error: error during rendering: /; error: {"stack":"Error: Module parse failed: Unexpected character '@' (268:0)\nYou may need an appropriate loader to handle this file type.\n| \n| \n> @import '~@styles/mixins.styl'\n| @keyframes headIn\n|   from\n    at eval (webpack-internal:///./node_modules/vue-loader/lib/index.js?!./src/app/components/Head.vue?vue&type=style&index=0&id=70c59da2&lang=stylus&scoped=true&:1:7)\n    at Object../node_modules/vue-loader/lib/index.js?!./src/app/components/Head.vue?vue&type=style&index=0&id=70c59da2&lang=stylus&scoped=true& (index.isomorphic.js:58:1)\n    at __webpack_require__ (isomorphic.js:27:30)\n    at eval (webpack-internal:///./src/app/components/Head.vue?vue&type=style&index=0&id=70c59da2&lang=stylus&scoped=true&:2:183)\n    at Module../src/app/components/Head.vue?vue&type=style&index=0&id=70c59da2&lang=stylus&scoped=true& (index.isomorphic.js:388:1)\n    at __webpack_require__ (isomorphic.js:27:30)\n    at VueComponent.injectStyles (webpack-internal:///./src/app/components/Head.vue:10:16)\n    at VueComponent.hook (webpack-internal:///./node_modules/vue-loader/lib/runtime/componentNormalizer.js:55:22)\n    at invokeWithErrorHandling (/Users/zhanghanbing/WebstormProjects/vuesion/node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)\n    at callHook (/Users/zhanghanbing/WebstormProjects/vuesion/node_modules/vue/dist/vue.runtime.common.dev.js:4201:7)","message":"Module parse failed: Unexpected character '@' (268:0)\nYou may need an appropriate loader to handle this file type.\n| \n| \n> @import '~@styles/mixins.styl'\n| @keyframes headIn\n|   from"}
debug: whole request: 54ms
[Vue warn]: Error in beforeCreate hook: "Error: Module parse failed: Unexpected character '@' (268:0)
You may need an appropriate loader to handle this file type.
| 
| 
> @import '~@styles/mixins.styl'
| @keyframes headIn
|   from"

found in

---> <PublicHead> at src/app/components/Head.vue
       <Index> at src/app/index/Index/Index.vue
         <App> at src/app/app/App/App.vue
           <Root>
```

**Comment by MohitTilwani15** [comment]
Hello @zhanghanbing1998 

Always happy to help. In Vuesion, there is a way you can override or add something on top of the existing webpack configuration. The above issue is because vuesion doesn't use stylus and hence there is no stylus and stylus loader installed. Follow the below steps and everything should work as you expect.

step1: `npm install stylus stylus-loader -D`

step2: Add `stylus loader` in `webpack.config.js` in `.vuesion` folder

```
config.module.rules.push({
    test: /\.styl(us)?$/,
      use: [
        'vue-style-loader',
        'css-loader',
        'stylus-loader'
      ],
    },
  );
```

Let me know if it works.

**Comment by zhanghanbing1998** [comment]
Thank you very much for your answer. I will have a test tomorrow.

**Comment by zhanghanbing1998** [comment]
@MohitTilwani15 I'm sorry to reply to you now. It's feasible after my test. Thank you very much.
