### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ludo1960** [vuesion/vuesion#420]
**Describe the bug**

When running npm install the script stalls when trying to install rxjs@5.5.12 I tried npm install -g rxjs@5.5.12 and running npm install again, but the same thing happens.

**Additional context**

When trying npm run dev here is log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.10.1
3 info using node@v12.6.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vuesion@3.2.3~predev: vuesion@3.2.3
6 info lifecycle vuesion@3.2.3~dev: vuesion@3.2.3
7 verbose lifecycle vuesion@3.2.3~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vuesion@3.2.3~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/vue/vuesion/node_modules/.bin:/home/ludo/.symfony/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle vuesion@3.2.3~dev: CWD: /var/vue/vuesion
10 silly lifecycle vuesion@3.2.3~dev: Args: [ '-c', 'vuesion dev -o' ]
11 info lifecycle vuesion@3.2.3~dev: Failed to exec dev script
12 verbose stack Error: vuesion@3.2.3 dev: `vuesion dev -o`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:203:13)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
13 verbose pkgid vuesion@3.2.3
14 verbose cwd /var/vue/vuesion
15 verbose Linux 4.9.0-9-amd64
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
17 verbose node v12.6.0
18 verbose npm  v6.10.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error vuesion@3.2.3 dev: `vuesion dev -o`
23 error spawn ENOENT
24 error Failed at the vuesion@3.2.3 dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by ludo1960** [comment]
Seems a dodgy wireless connection was the problem. Installed from a wired connection and it installs no problem
